name: gaps

on:
  push:
    branches: [ "develop" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    # Test job
    push_to_gasp:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - uses: namaggarwal/clasp-token-action@v0.0.1
        with:
            client-id: ${{ secrets.GAPS_CLIENT_ID }}
            client-secret: ${{ secrets.GAPS_CLIENT_SECRET }}
            refresh-token: ${{ secrets.GAPS_REFRESH_TOKEN }}
      - name: Install clasp
        id: install-clasp
        run: sudo npm install @google/clasp -g
      - name: Push script to scripts.google.com
        id: clasp-push
        run: node .\push.mjs push
