name: Local CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:




jobs:
  test_local:
    uses: fletort/test-app-script/.github/workflows/model_test_local.yml@develop
  # doc job
  generate_doc:
    uses: fletort/test-app-script/.github/workflows/model_generate_doc.yml@develop
    if: github.ref == 'refs/heads/develop'

  # Deployment doc & testresult
  deploy_doc:
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: fletort/test-app-script/.github/workflows/model_deploy_doc.yml@develop
    needs: [test_local, generate_doc]
    if: github.ref == 'refs/heads/develop'


  